version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1987
      POSTGRES_DB: tmb_db
    ports:
      - "8002:5432"
    networks:
      - webapp-network

  webapp:
    image: backend-tmbapplication:latest
    build:
      context: ./backend/api-tmb
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=Host=db;Port=5432;Username=admin;Password=1987;Database=tmb_db
      - AZURE_SERVICE_BUS=${AZURE_SERVICE_BUS}
      - AZURE_SERVICE_QUEUE=tmb-queue
    networks:
      - webapp-network
    command: >
      sh -c "ApiTmb.dll"
    depends_on:
      - db
    restart: always

  frontend:
    image: frontend-tmbapplication:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
